#pragma once

// clang-format off
// generated by /usr/local/bin/sqlpp23-ddl2cpp --path-to-ddl DarkDrives.sql --namespace db --path-to-header-directory definition --generate-table-creation-helper --use-import-std

#include <sqlpp23/core/name/create_name_tag.h>

import std;



#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/type_traits.h>

namespace db {
  template<typename Db>
  void createExifField(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS exif_field)+++");
    db(R"+++(CREATE TABLE `exif_field` (
  `field_id` smallint(6) NOT NULL,
  `name` varchar(128) NOT NULL,
  PRIMARY KEY (`field_id`)
))+++");
  }

  struct ExifField_ {
    struct FieldId {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(field_id, fieldId);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(exif_field, exifField);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               FieldId,
               Name>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<ExifField_>, FieldId>,
               sqlpp::column_t<sqlpp::table_t<ExifField_>, Name>>;
  };
  using ExifField = ::sqlpp::table_t<ExifField_>;


} // namespace db
