#pragma once

// clang-format off
// generated by /usr/local/bin/sqlpp23-ddl2cpp --path-to-ddl DarkDrives.sql --namespace db --path-to-header-directory definition --generate-table-creation-helper --use-import-std

#include <sqlpp23/core/name/create_name_tag.h>

import std;



#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/type_traits.h>

namespace db {
  template<typename Db>
  void createFileOutput(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS file_output)+++");
    db(R"+++(CREATE TABLE `file_output` (
  `inode` bigint(20) unsigned NOT NULL,
  `file_output` varchar(20000) NOT NULL,
  PRIMARY KEY (`inode`)
))+++");
  }

  struct FileOutput_ {
    struct Inode {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(inode, inode);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct FileOutput {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(file_output, fileOutput);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(file_output, fileOutput);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Inode,
               FileOutput>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<FileOutput_>, Inode>,
               sqlpp::column_t<sqlpp::table_t<FileOutput_>, FileOutput>>;
  };
  using FileOutput = ::sqlpp::table_t<FileOutput_>;


} // namespace db
