#pragma once

// clang-format off
// generated by /usr/local/bin/sqlpp23-ddl2cpp --path-to-ddl DarkDrives.sql --namespace db --path-to-header-directory definition --generate-table-creation-helper --use-import-std

#include <sqlpp23/core/name/create_name_tag.h>

import std;



#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/type_traits.h>

namespace db {
  template<typename Db>
  void createInode(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS inode)+++");
    db(R"+++(CREATE TABLE `inode` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `parent` bigint(20) unsigned DEFAULT NULL,
  `type` enum('DRIVE','DIR','FILE','LINK') DEFAULT NULL,
  `name` char(255) NOT NULL,
  `c_time` datetime NOT NULL,
  `m_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `parent_name` (`parent`,`name`)
))+++");
  }

  struct Inode_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::true_type;
    };
    struct Parent {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(parent, parent);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct Type {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(type, type);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    struct CTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(c_time, cTime);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct MTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(m_time, mTime);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(inode, inode);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Parent,
               Type,
               Name,
               CTime,
               MTime>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<Inode_>, Name>,
               sqlpp::column_t<sqlpp::table_t<Inode_>, CTime>,
               sqlpp::column_t<sqlpp::table_t<Inode_>, MTime>>;
  };
  using Inode = ::sqlpp::table_t<Inode_>;


} // namespace db
