#pragma once

// clang-format off
// generated by /usr/local/bin/sqlpp23-ddl2cpp --path-to-ddl DarkDrives.sql --namespace db --path-to-header-directory definition --generate-table-creation-helper --use-import-std

#include <sqlpp23/core/name/create_name_tag.h>

import std;



#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/type_traits.h>

namespace db {
  template<typename Db>
  void createMimeType(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS mime_type)+++");
    db(R"+++(CREATE TABLE `mime_type` (
  `id` int(10) unsigned NOT NULL,
  `mime_type` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mime_type` (`mime_type`)
))+++");
  }

  struct MimeType_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct MimeType {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(mime_type, mimeType);
      using data_type = ::sqlpp::text;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(mime_type, mimeType);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               MimeType>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<MimeType_>, Id>,
               sqlpp::column_t<sqlpp::table_t<MimeType_>, MimeType>>;
  };
  using MimeType = ::sqlpp::table_t<MimeType_>;


} // namespace db
