#pragma once

// clang-format off
// generated by /usr/local/bin/sqlpp23-ddl2cpp --path-to-ddl DarkDrives.sql --namespace db --path-to-header-directory definition --generate-table-creation-helper --use-import-std

#include <sqlpp23/core/name/create_name_tag.h>

import std;



#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/type_traits.h>

namespace db {
  template<typename Db>
  void createStats(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS stats)+++");
    db(R"+++(CREATE TABLE `stats` (
  `inode` bigint(20) unsigned NOT NULL,
  `mode` smallint NOT NULL,
  `uid` int(10) unsigned NOT NULL,
  `gid` int(10) unsigned NOT NULL,
  `size` bigint(20) unsigned NOT NULL,
  `blksize` bigint(20) unsigned NOT NULL,
  `blkcnt` bigint(20) unsigned NOT NULL,
  `a_time` datetime NOT NULL,
  `m_time` datetime NOT NULL,
  `c_time` datetime NOT NULL,
  `mime_type` int(10) unsigned NOT NULL,
  PRIMARY KEY (`inode`)
))+++");
  }

  struct Stats_ {
    struct Inode {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(inode, inode);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct Mode {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(mode, mode);
      using data_type = ::sqlpp::integral;
      using has_default = std::false_type;
    };
    struct Uid {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(uid, uid);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct Gid {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(gid, gid);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct Size {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(size, size);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct Blksize {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(blksize, blksize);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct Blkcnt {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(blkcnt, blkcnt);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    struct ATime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(a_time, aTime);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct MTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(m_time, mTime);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct CTime {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(c_time, cTime);
      using data_type = ::sqlpp::timestamp;
      using has_default = std::false_type;
    };
    struct MimeType {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(mime_type, mimeType);
      using data_type = ::sqlpp::unsigned_integral;
      using has_default = std::false_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(stats, stats);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Inode,
               Mode,
               Uid,
               Gid,
               Size,
               Blksize,
               Blkcnt,
               ATime,
               MTime,
               CTime,
               MimeType>;
    using _required_insert_columns = sqlpp::detail::type_set<
               sqlpp::column_t<sqlpp::table_t<Stats_>, Inode>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Mode>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Uid>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Gid>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Size>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Blksize>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, Blkcnt>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, ATime>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, MTime>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, CTime>,
               sqlpp::column_t<sqlpp::table_t<Stats_>, MimeType>>;
  };
  using Stats = ::sqlpp::table_t<Stats_>;


} // namespace db
